name: Test-Test

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test-test:
    # Name the Job
    name: Test test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Gets added or modified files
      - name: Changed files
        uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: 'json'
        # Workaround for bug with this action
        # See: https://github.com/jitterbit/get-changed-files/issues/11#issuecomment-718254652
        continue-on-error: true
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Filter changed files
        id: filtered_files
        run: |
          filtered_files=""

          snapshots_path='cypress/snapshots';

          echo "${{ steps.files.outputs.all }}"

          #for changed_file in ${{ steps.files.outputs.all }} ; do
          #  if [[ $changed_file =~ $snapshots_path ]] ; then
          #    #echo "File: ${changed_file}."
          #    filtered_files="$filtered_files * $changed_file "
          #  fi
          #done

          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')

          for file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."

            if [[ $file =~ $snapshots_path ]] ; then
              filtered_files="$filtered_files * $file "
            fi
          done

          echo "$filtered_files"

          echo ::set-output name=filtered_files::"$filtered_files"

      - name: Post comment
        uses: mshick/add-pr-comment@v1
        if: steps.filtered_files.outputs.filtered_files != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            👀📎

            It looks like this PR contains the following visual snapshot changes:
            ${{ steps.filtered_files.outputs.filtered_files }}

            👉 Review the snapshot diffs <a href="${{ github.event.number }}/files?file-filters%5B%5D=.png">here</a>.

            If these changes are as expected, you can locally run the `yarn run test:e2e:update` command to update them.
          allow-repeats: true
